name             'simple-chef-tools'
maintainer       'YOUR_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures simple-chef-tools'
long_description 'Installs/Configures simple-chef-tools'
version          '0.1.0'
